export const COLORS_SIZE = 10;
export const SELECT_COLOR = 'SELECT_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SELECT_ALL_COLORS = 'SELECT_ALL_COLORS';
export const REMOVE_ALL_COLORS = 'REMOVE_ALL_COLORS';