export const MAIN_COLOR ='#3B97D3';
export const MIXED_COLOR = '#894B9D';

export const COLORS_SIZE = 10;
export const SHADE_RATIO = -0.1;
export const MIX_RATION = 0.2;

export const CHANGE_MAIN_COLOR = 'CHANGE_MAIN_COLOR';
export const CHANGE_MIXED_COLOR = 'CHANGE_MIXED_COLOR';

export const SELECT_COLOR = 'SELECT_COLOR';
export const SELECT_COLORS = 'SELECT_COLORS';
export const REMOVE_COLOR = 'REMOVE_COLOR';

export const CHANGE_SHADE_THEME = 'CHANGE_SHADE_THEME';
export const CHANGE_MIXED_THEME = 'CHANGE_MIXED_THEME';

export const SELECT_ALL_COLORS = 'SELECT_ALL_COLORS';
export const REMOVE_ALL_COLORS = 'REMOVE_ALL_COLORS';